### ISSUE TITLE
Add GitHub Actions for Code Analysis

### ISSUE THREAD

**Issue by breakcraft** [breakcraft/Auto-GPT-Plugin-Template#1]
Create a GitHub Actions workflow file to automatically run code analysis using flake8 and pytest. This will help maintain code quality by checking for linting errors and running tests on each push or pull request to the master branch.

### Workflow File

```yaml
name: Code Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        run: |
          pytest
```

### Steps to Commit
1. Navigate to `.github/workflows` in your repository.
2. Create a new file named `code-analysis.yml`.
3. Add the above workflow content.
4. Commit and push the changes.

This setup will trigger the workflow on each push or pull request to the master branch.
